name: Backpacks
version: '1.0-SNAPSHOT'
main: main.Main
api-version: 1.18
commands:
  backpack:
    description: "Backpack Plugin by GunterPro7"
    usage: "/backpack"
  bp:
    description: "Backpack Plugin by GunterPro7"
    usage: "/bp"
