name: Waypoint
version: '${project.version}'
main: main.Main
api-version: 1.14
commands:
  waypoint:
    description: "Waypoint command"
    usage: "/waypoint"
  wp:
    description: "Waypoint command"
    usage: "/wp"
